### ISSUE TITLE
Nachrichten

### ISSUE THREAD

**Issue by patreu22** [patreu22/Twittex#58]
Tasks:
- DB model und Dokumentation(ER-Diagramm) erweitern
- Privatnachricht anzeigen 
- Nachricht lesen
- Nachricht schreiben
- Nachricht senden

**Comment by Krymnos** [comment]
Done:
- DB model und Dokumentation(ER-Diagramm) erweitern
- Nachricht schreiben
- Nachricht senden
- Privatnachricht anzeigen 
- Nachricht lesen
